### ISSUE TITLE
Discussion Wishlist

### ISSUE THREAD

**Issue by marcosci** [marcosci/landscapemetrics#10]
1. @Nowosad what do you think about parallelization? Is one dependency more worth the speed gain?

2. I assume you also added sf support: That would be just a wrapper around `rasterize`, or?

**Comment by Nowosad** [comment]
I think that, for now, we should prioritize building a perfectly working one-core, raster-based  package. This kind of improvement can be a phase two of the project;)

**Comment by jhollist** [comment]
Also haven't looked at the code base (y'all been busy!) but if raster::rasterize is used, I would take a close look at fasterize::fasterize.  The speed up would be worth the extra dependency.
