### ISSUE TITLE
Bugs in FRAGSTATS

### ISSUE THREAD

**Issue by marcosci** [marcosci/landscapemetrics#13]
... our in Max's and my head.

A short list here to collect everything:

- Patches with 1 cell get a CIRCLE metric of 0, should be something around 0.36 instead
    - Sometimes the abbreviation is CIRCLE, sometimes SQUARE
- A mixup between hectare and meter in documentation and code
    - Perimeter-Area Ratio (PARA)

**Comment by mhesselbarth** [comment]
Perimeter-Area Ratio (PARA). They divided through the area in ha (however, documentation says use area in m^2)

**Comment by mhesselbarth** [comment]
The shape index on patch levels seems a bit odd to me

**Comment by mhesselbarth** [comment]
FRAGSTATS rounds after the 3rd digit, e.g.  a cell size of x = 0.002777778 is x = 0.003 in FRAGSTATS. This may lead to different results for several metrics

**Comment by marcosci** [comment]
Mismatch of our sd and cv and the ones in FRAGSTATS. I am fairly certain that the implementation in R of sd() is correct ...
