### ISSUE TITLE
show_patches 

### ISSUE THREAD

**Issue by Nowosad** [marcosci/landscapemetrics#14]
Shouldn't `show_patches()` be a part of the **landscapetools** package? What do you think?

**Comment by marcosci** [comment]
If Max is fine with that, it probably makes sense :)

**Comment by mhesselbarth** [comment]
I'm fine with that, sure

**Comment by marcosci** [comment]
show_patches is now in landscapetools

**Comment by marcosci** [comment]
Max just pointed out that it also makes sense to do the same with cclabel and pad_raster (or make pad_raster just an internal function, there is probably no actual use case for that).

Everyone fine with that?

**Comment by Nowosad** [comment]
Can we wait a few weeks for a decision about it? I am going to add a piece of rcpp code in the (near) future and we can decide what do to with all of it;)

**Comment by marcosci** [comment]
Sure thing :)

**Comment by marcosci** [comment]
Max and I piggybacked show_patches back into the package and Max also included show_correlation.
We think that it is at least a good point for the planned publication, but also in the context of including some functions to select metrics and/or look at the results.

Fine with you @Nowosad ? Completely open for arguments against that.

**Comment by Nowosad** [comment]
I do not have a strong opinion here. Will let you know if I would have one;)
