### ISSUE TITLE
lsm_c_ed -> subscript out of bounds

### ISSUE THREAD

**Issue by bitbacchus** [marcosci/landscapemetrics#17]
I get an error message with this function:

`> lsm_c_ed(landscape)

Error in `[.default`(tb, 2:ncol(tb), 1) : subscript out of bounds`

The error seems to occur in file lsm_c_te.R line 112, but I couldn't figure out the details. The error occurred also before commit 086c1d20106540803a71195f810b67ea246c37ab . 

I attached two landscape files (please rename to .asc), one that triggers the error, one that doesn't. A minimal example to trigger the error would be:

`
landscape <- raster("landscape.asc")
lsm_c_ed(landscape) # error

landscape <- raster("landscape_ok.asc")
lsm_c_ed(landscape) # no error
`

Please let me know if I can give any support.

Best,
Sebastian

[landscape.txt](https://github.com/marcosci/landscapemetrics/files/2145416/landscape.txt)
[landscape_ok.txt](https://github.com/marcosci/landscapemetrics/files/2145417/landscape_ok.txt)

**Comment by mhesselbarth** [comment]
Seems like there is a bug in lsm_c_te() because in the "wrong" landscape there is only one patch of one class, so there is basically no edge. We will fix that specially case so that it returns 0.

**Comment by mhesselbarth** [comment]
Should be fixed...

**Comment by heislele** [comment]
Hello,

I am getting the above error when using sample_lsm to call lsm_c_ed, lsm_c_para_mn, and lsm_c_cohesion. For example:

Load land cover raster
>lc2000 <- raster('LC2000_ORIGINAL.img')

Set up sample locations (points)
>ghow <- read.csv('GHOW.csv', row.names = 1)
>buow <- read.csv('BUOW.csv', row.names = 1)
>owl <- rbind(buow, ghow)
>IDED <- rowSums(owl[,6:17])
>RICH <- rowSums(owl[,6:17] !=0)
>owl <- cbind(owl[,1:5], IDED, RICH, owl[,6:17])
>buow <- subset(owl, OWL == 'BUOW')
>buow <- subset(buow, IDED >= 10)
>ghow <- subset(owl, OWL == 'GHOW')
>ghow <- subset(ghow, IDED >= 30)
>owl <- rbind(buow, ghow)
>proj <- projection(lc2000)
>owl <- SpatialPointsDataFrame(owl[,2:3], owl, proj4string = CRS('+proj=longlat +datum=WGS84'))
>owl <- spTransform(owl, CRS(proj))

Calculate edge density within 500m of each sample location (i.e., owl)
>ed1km <- sample_lsm(lc2000, owl.sp, shape='square', size=500, what='lsm_c_ed')

Error in neighbor_matrix[2:ncol(neighbor_matrix), 1] : subscript out of bounds

[drive-download-20190415T204715Z-001.zip](https://github.com/r-spatialecology/landscapemetrics/files/3082112/drive-download-20190415T204715Z-001.zip)

Any help with this error would be greatly appreciated! Also, congratulations on developing this package, it is AWESOME!

Cheers,
Leanne Heisler
