### ISSUE TITLE
Vignettes R CMD CHECK note 

### ISSUE THREAD

**Issue by marcosci** [marcosci/landscapemetrics#23]
Does someone know how to avoid this note?

```r
N  checking for unstated dependencies in vignettes ...
   '::' or ':::' import not declared from: ‘landscapetools’
   'library' or 'require' call not declared from: ‘patchwork’
```

We have a couple of "vignettes" that are only meant for the homepage.
They are in `vignettes/articles`, which is included in .Rbuildignore and I stripped everything related to vignettes from the yaml header - but the R CMD CHECK still thinks they would end up in the package?

**Comment by Nowosad** [comment]
I think that the patchwork package needs to be added as Suggests to the Description file. 
It should fix this problem.

**Comment by Nowosad** [comment]
Ok, that is only a part of the problem. The **patchwork** package is not on CRAN yet. A temporary solution is to add "Remotes: thomasp85/patchwork" to Description. However, this is (I think) unacceptable for CRAN.

**Comment by marcosci** [comment]
It is. I think I fixed it, but then again `check` is a huge mystery for me sometimes.
Apparently one can use whatever package you want for the homepage, as long as you load them via `library` and not `::`.

https://github.com/marcosci/landscapemetrics/commit/07ccd09e4393c8a1648601f8821f7befa21a0b67

**Comment by mhesselbarth** [comment]
Do we really need the patchwork package? We just use it to plot two ggplot2 next to each other, right? Maybe we could just solve that differently

**Comment by marcosci** [comment]
No, I just used it for plots on the webpage. But should be fixed now.
