### ISSUE TITLE
Use of tic instead of manualy rebuilding the website each time

### ISSUE THREAD

**Issue by Nowosad** [marcosci/landscapemetrics#25]
https://github.com/ropenscilabs/tic

**Comment by marcosci** [comment]
done as suggested

**Comment by marcosci** [comment]
I lost against tic ... @Nowosad do you know how to configure it so that it only updates the docs folder and does **not** the whole master branch ? :stuck_out_tongue:

**Comment by marcosci** [comment]
Nevermind, works ... sorry :)
