### ISSUE TITLE
Vignette New Metrics

### ISSUE THREAD

**Issue by marcosci** [marcosci/landscapemetrics#28]
Hey Jakub,

I started a vignette about new metrics in landscapemetrics that are not from FRAGSTATS.
The idea is to shed some light on them and that they don't drown in the masses of metrics coming from FRAGSTATS:

https://marcosci.github.io/landscapemetrics/articles/articles/new_metrics.html

I would reference every paper there and link the functions. I think it would be nice to have 3,4 sentences briefly describing them under the quote - would it be OK for you to write something about yours there? :relaxed:

**Comment by Nowosad** [comment]
Yes, yes, yes.

**Comment by Nowosad** [comment]
I've added a short description a few minutes ago - https://github.com/marcosci/landscapemetrics/commit/3ba7f760627e5f649822a5236eaa9d6198b24b11. My plan is also to add several examples, but due to my other commitments - it will probably happen sometime next month..

**Comment by marcosci** [comment]
Awesome job :-) Thanks!
