### ISSUE TITLE
Edges

### ISSUE THREAD

**Issue by marcosci** [marcosci/landscapemetrics#5]
Hi metrics hivemind,

is there any preferred strategy for edge detection?

We polygonized raster and dissolved them so far, which is quite fast with gdal_polygonize - but that would make the dependencies quite heavy. In some issues in fasterize and sf they spoke about implementing that, but I have not seen it so far.

Borrowing C++ code for connected labeling (the way SDMTools does it) is the other alternative - with the problem that you have to do that always for each class separately and have to go lengths to calculate edge length etc (as one can't simply calculate the length of the perimeter of a polygon). 

Is there any preference for one of the two approaches?

**Comment by Nowosad** [comment]
For my internal project, I have used `spex::polygonize()`, but I assume there could be a better way, e.g.:

```R
total_edge = function(input_raster){
  input_raster = setValues(raster(input_raster), input_raster[])
  output_edges = polygonize(input_raster) %>% 
    st_as_sf() %>% 
    aggregate(list(.$layer), function(x) x[1]) %>% 
    mutate(id = 1)  %>% 
    st_cast("MULTILINESTRING") %>% 
    aggregate(list(.$id), function(x) x[1])
  
  output_boundaries = st_bbox(input_raster) %>% 
    st_as_sfc() %>% 
    st_cast("LINESTRING")
  
  # all edges minus the boundary
  total_edge = st_length(output_edges) - st_length(output_boundaries)
  total_edge
}
```

**Comment by mhesselbarth** [comment]
I worked on a similar approach: 

```
library(landscapemetrics)
library(raster)
library(sf)

value_name <- names(landscape)

landscape %>%
    spex::polygonize() %>%
    dplyr::group_by_(value_name) %>%
    dplyr::summarise() %>%
    sf::st_cast('MULTILINESTRING') %>%
    sf::st_length()
```

However, for larger raster it gets pretty slow (or at least not really fast...)

**Comment by Nowosad** [comment]
Surprisingly (?) our codes are almost identical:). In my option, we should focus on main functions and we can optimize them later. 

Btw `group_by_()` (and other similar functions) are deprecated. Therefore we should avoid using them in this package...

**Comment by marcosci** [comment]
I just pushed some C++ code for connected component labeling which can be used with the `cclabel` function:

https://github.com/marcosci/landscapemetrics/blob/master/R/cclabel.R

If we count the raster cells with NA neighbors and how many there are for each patch we also get the edge length. As soon as that is implemented, we can check how the performance differs between that and the spex way.

But overall, my gut feeling is that not going the polygon way is more precise and further metrics that are related to patch shape could be more easily derived from the results from connected labeling.

**Comment by Nowosad** [comment]
@marcosci What is the source of this code? Should we add its author to Description?

**Comment by marcosci** [comment]
It's from the R package ccoutline, which is currently only on github. I referenced the author of the package in the function - if we plan to keep it I am more than happy with including him as one of the authors :)

It looks actually quite good performance wise so far (this is counting the edge length and the difference becomes bigger and bigger with increasing raster size):

![image](https://user-images.githubusercontent.com/10864574/39888304-befb250c-5494-11e8-8ab0-9f3e9c838487.png)

Do you have any major concerns with this approach and want to stick to the polygon option?

**Comment by marcosci** [comment]
So, I just pushed a version that can also handle rasterstacks/bricks and implemented 2 metrics with it - I think it works quite nice and it produces the same results as your total_edge function.

Shall we stick with it?

**Comment by laurajanegraham** [comment]
I've just been looking at the mean Euclidean nearest neighbour calculation. I was intending to do this with rasterToPolygons and disaggregate, but it makes sense to avoid polygonisation completely given your discussion here. 

If you have any advice on how to use this method to calculate distances between patches please let me know. I had a brief look today, but end of Friday was probably not the best time to start on it!

**Comment by marcosci** [comment]
The only way I can come up with right now that does not involve polygons are:

1. Label the individual patches for each class and use `distance` from *raster* for every pair of patches. Then select the cells with the lowest values, as these should be the Euclidean distance.

... the "problem" with the metric is that is accounts for the patch edges - I can't come up with a clever to way to identify the edge with the minimum distance to a neighboring patch (then it would just be the Pythagorean theorem). By the way - doesn't the distance in polygon operations also accounts for the centroid and not the edges? 

But I would try out the described heuristic approach and will let you know :nerd_face:

**Comment by kawith** [comment]
Sounds like you are pretty deep into the code at this point, but just to clarify that the ENN is being assessed from patch edge to patch edge (and not the patch centroids), correct?  The patch edge-to-edge distance is preferred, and my understanding is that Fragstats identifies the two cells that are closest between neighboring patches of the same type, and calculates the Euclidean distance between those cell centers.  I think that is pretty much what you are suggesting, Marco, yes?

**Comment by laurajanegraham** [comment]
My original plan was to convert to polygon and use gDistance from rgeos - this gives edge-to-edge distances.

**Comment by marcosci** [comment]
Did you implement that somewhere @laurajanegraham ?

I pushed a version that works without polygonization:

https://github.com/marcosci/landscapemetrics/blob/master/R/lsm_c_enn_mn.R

... in my mind it makes sense, but maybe better double check it with your version and fragstats :)

It again labels all the patches and then calculates the euclidian distances pairwise for every patch.
The patches are courced to to an xy-matrix and the location is always the cell center (as described in the fragstats manual).

Maybe it's even faster if we first select the edges with `raster::boundaries`, but so far it looks quite decent.

**Comment by laurajanegraham** [comment]
Hi @marcosci, I didn't get around to implementing it so it's probably best to just check against FRAGSTATS.

**Comment by marcosci** [comment]
will do :) at the moment we are way off, have to figure out why.

**Comment by marcosci** [comment]
It produces now the same results as FRAGSTATS. 

I will close the issue here - if anyone has concerns about the connected component labeling, please reopen.
