### ISSUE TITLE
Functions structure 

### ISSUE THREAD

**Issue by Nowosad** [marcosci/landscapemetrics#6]
Hey all!

I've opened this issue to discuss the internal structure of functions in this package.
**Main idea:**

1. Don't repeat yourself. Most of the functions have the same/similar code twice - one for RasterLayer and second time for RasterStack/Brick, for example - https://github.com/marcosci/landscapemetrics/blob/master/R/lsm_l_shei.R. I would think there is a better way to handle it. Please take a look at my gist - https://gist.github.com/Nowosad/27341392f3053eab657efbe3cd42e999. It has only one main function (`lsm_l_shei_calc`) and the rest is just method calls. What do you think about it? I assume it also can be improved, but it is a step in right direction (in my opinion).

**Minor ideas:**

1. We should use `as.integer()` instead of `as numeric()` for the layer or the id number.
2. Consistent coding style is very helpful and it looks really good now. However, the only inconsistent thing that I've found is the use of single (`'`) and double (`"`) quotation marks. I would suggest that we stick to the double quotes.
3. I would suggest using `seq_len(nlayers(landscape))` instead of `1:raster::nlayers(landscape)`. In our case it is not a big deal, but it is a better programming style and helps to avoid problems in some cases (http://www.win-vector.com/blog/2018/02/r-tip-use-seq_len-to-avoid-the-backwards-sequence-bug/).

Let me know what you think about it. I am looking forward to your comments!
J.

**Comment by marcosci** [comment]
Thanks, Jakub. All of your suggestions make perfect sense (especially the first one, I knew the method dispatch - but I think I used it not in the right way so far. Your example was a little eye-opener.)

**Comment by marcosci** [comment]
What we are missing in every function so far are argument checks  - any concerns about checkmate?

**Comment by Nowosad** [comment]
Can you create and post some examples of using it, Marco? I am curious in which cases it would be needed.

**Comment by marcosci** [comment]
Another thing would be to check for the resolution. 
So far we assume the x and y resolution for a lot of the calculations of the area.
