### ISSUE TITLE
Validation of the metrics

### ISSUE THREAD

**Issue by Nowosad** [marcosci/landscapemetrics#8]
I think that functions validation is essential in projects like this one. Thus, I suggest the following steps after implementing all of basic metrics (in order):

- [x] 1. Create a diverse set of test examples. Dimensions: (a) input type (e.g. RasterLayer vs RasterStack), (b) number of classes (e.g. binary vs 5-classes), (c) data availability (e.g. full data vs some missing values), (d) distribution of values (e.g. random vs aggregated). [Am I missing something here?]
- [x] 2. Calculate all of the metric using FRAGSTATS. Save the results.
- [x] 3. Create a bunch of tests using **testthat**. They should compare our results and the FRAGSTATS's ones.
- [ ] 4. The test (and codecov) should also show where we need to add some argument tests (https://github.com/marcosci/landscapemetrics/issues/6#issuecomment-388835850). 

As always - it is just my idea. I am interested in your opinions!

**Comment by mhesselbarth** [comment]
I calculated basically all FRAGSTATS metrics for the *landscape* raster. 

[landscape_fragstats.xlsx](https://github.com/marcosci/landscapemetrics/files/2004987/landscape_fragstats.xlsx)

**Comment by Nowosad** [comment]
That's great @mhesselbarth! My plan for this afternoon is to create a group of test examples.

**Comment by mhesselbarth** [comment]
Ups...turns out there are some bugs in the edge/perimeter calculations what to thread as edge. Needs some bug fixes...I will push a fixed version hopefully soon.

**Comment by mhesselbarth** [comment]
We also need to think about the units, e.g. the area in FRAGSTATS is always in hectare (and the user can specify the size of the input cells in meter).  Of course, this also leads to differences in e.g. the parameter-area ratio (however, just in the decimal place, but still...).

**Comment by Nowosad** [comment]
My proposed testing datasets:

![](https://i.imgur.com/oVO5BLf.png)

1 - two classes aggregated
2 - two classes disaggregated
3 - three classes aggregated
4 - three classes disaggregated
5 - two classes + NA values
6 - three random classes 

What do you think?

**Comment by marcosci** [comment]
Seems to be a rigorous set of landscape patterns to test against.
Do you want to run them through FRAGSTATS and in the testthat test suite compare against our functions?
