### ISSUE TITLE
Whishlist

### ISSUE THREAD

**Issue by mhesselbarth** [marcosci/landscapemetrics#9]
Ideas for the future:

- [ ] Adding the class to show_patches()
- [ ] Use future-package for parallel computation
- [x] Function that runs every metric with the option to only run for patch, class or landscape scale (`calculate_metrics(landscapes, what = "all")`)
- [ ] Support for non-raster data, for example `sf` objects
- [ ] Vignette
     - [ ] Subvignette with a 3 column facet plot. Every row is one metric, every column represents from left to right a low, medium and high value of the corresponding metric. The plot itself is a landscape (most likely from NLMR) with the same characteristic described by the metric.

**Comment by Nowosad** [comment]
@marcosci I added your great idea to the first post. This way it will be easier to organize this issue;) (I am going to delete my message in an hour)
